package com.example.doctor.ui.util

const val PATIENT_INFO_DESTINATION = "CUSTOMER_INFO_DESTINATION"
const val DOCTOR_INFO_DESTINATION = "DOCTOR_INFO_DESTINATION"
const val APPOINTMENT_CONFIRMATION_DESTINATION = "APPOINTMENT_CONFIRMATION_DESTINATION"
const val APPOINTMENT_CONFIRMED_DESTINATION = "APPOINTMENT_CONFIRED_DESTINATION"
const val EDIT_PATIENT_INFO_DESTINATION = "EDIT_PATIENT_INFO_DESTINATION"
const val EDIT_CONTACT_DETAILS_DESTINATION = "EDIT_CONTACT_DETAILS_DESTINATION"
const val CUSTOMER_NAME = "CUSTOMER_NAME"
const val BASE_URL = "BASE_URL"
const val DOCTOR_TEXT = "Dr. "
const val EDIT_CONTACT_PHONE_NUMBER = "EDIT_CONTACT_PHONE_NUMBER"
const val EDIT_CONTACT_EMAIL = "EDIT_CONTACT_EMAIL"
const val INSURANCE_NAME = "INSURANCE_NAME"
const val INSURANCE_LIST = "INSURANCE_LIST"

//sample user credentials
const val USER1 = "user1"
const val PASSWORD = "123"
const val USER2 = "user2"

